version: "3"
services:
  app-db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=indira
      - MYSQL_DATABASE=wanderers_way
  app:
    build: .
    ports:
      - "8082:8082"
    depends_on:
      - app-db