version: "3"
services:
  app-db:
    restart: always
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=indira
      - MYSQL_DATABASE=wanderers_way
    ports:
      - "3307:3306"
  app:
    build: .
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://app-db:3306/database?autoReconnect=true&useSSL=false
    depends_on:
      - app-db